name = "OpenMath"
uuid = "a3e62119-7808-4860-a560-991581b033be"
version = "0.1.0"
authors = ["Sébastien Celles <s.celles@gmail.com> and contributors"]

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
XML = "72c71f33-b9b6-44de-8c94-c961784809e2"

[weakdeps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[sources]
XML = {rev = "main", url = "https://github.com/JuliaData/XML.jl"}

[extensions]
OpenMathSymbolicsExt = "Symbolics"

[compat]
PrecompileTools = "1"
Symbolics = "5, 6, 7"
XML = "0.4"
julia = "1.10"
