# SPDX-License-Identifier: MIT
#
# Sets up the differential oracle: clones the reference crate, writes the wrapper
# and builds it. Run by `just oracle-setup`.
#
# The oracle is deliberately **not** part of CI. It needs a Rust toolchain and a
# network clone, and the binary it produces links GPL-3 code. Putting it in the
# pipeline would make every build depend on a third-party repository staying
# reachable, which contradicts the hermeticity the verifier promises, and would
# build GPL-3 artefacts inside the pipeline of an MIT package. It is an opt-in
# command instead, run when someone wants the answer.
#
# This script is MIT, like the rest of the package. The Rust it writes is marked
# GPL-3.0-or-later because it links the GPL-3 `openmath` crate, and it is written
# into refs/, which is gitignored and never distributed.

const ROOT = normpath(joinpath(@__DIR__, "..", ".."))
const REFS = joinpath(ROOT, "refs")
const REFERENCE = joinpath(REFS, "rust-openmath")
const ORACLE = joinpath(REFS, "om-oracle")

const REFERENCE_URL = "https://github.com/FlexiFormal/OpenMath.git"

# Pinned, so that a disagreement is reproducible and `upstream-bugs.md` can name
# exactly what was tested. Bump deliberately, never incidentally.
const REFERENCE_COMMIT = "06d279713843b6909e8f476635dfad7a18f83cd7"
const CRATE_VERSION = "0.1"

const CARGO_TOML = """
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Generated by test/harness/oracle_build.jl — edit that, not this.
#
# A differential-testing oracle for OpenMath.jl. It links the GPL-3 `openmath`
# crate, so this wrapper is GPL-3 too, which is why it lives under refs/,
# gitignored and outside the MIT package, and is never distributed.
[package]
name = "om-oracle"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
openmath = { version = "$CRATE_VERSION", features = ["serde"] }
serde_json = { version = "1", features = ["arbitrary_precision"] }

[profile.release]
opt-level = 1
"""

const MAIN_RS = raw"""
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Generated by test/harness/oracle_build.jl — edit that, not this.
//
// Reads an OpenMath document on stdin and re-emits it, using the reference
// implementation. OpenMath.jl pipes its corpus through this and compares the
// result against its own, so that a disagreement is either our bug or an
// upstream finding.
//
//   om-oracle xml    XML in, XML  out
//   om-oracle json   XML in, JSON out

use std::io::{self, Read};

use openmath::{de::OMObject as DeObject, OMSerializable, OpenMath};

fn main() {
    let mode = std::env::args().nth(1).unwrap_or_else(|| "xml".to_string());
    let mut input = String::new();
    if let Err(e) = io::stdin().read_to_string(&mut input) {
        eprintln!("om-oracle: cannot read stdin: {e}");
        std::process::exit(2);
    }

    let parsed = match DeObject::<OpenMath>::from_openmath_xml(&input) {
        Ok(v) => v,
        Err(e) => {
            eprintln!("om-oracle: parse error: {e}");
            std::process::exit(1);
        }
    };

    match mode.as_str() {
        "xml" => println!("{}", parsed.omobject().xml(false, true)),
        "json" => match serde_json::to_string(&parsed.omobject()) {
            Ok(s) => println!("{s}"),
            Err(e) => {
                eprintln!("om-oracle: serialisation error: {e}");
                std::process::exit(1);
            }
        },
        other => {
            eprintln!("om-oracle: unknown mode {other:?}; expected xml or json");
            std::process::exit(2);
        }
    }
}
"""

function have(tool)
    return try
        success(pipeline(`$tool --version`; stdout = devnull, stderr = devnull))
    catch
        false
    end
end

function fetch_reference()
    if isdir(REFERENCE)
        println("  reference: already present")
    else
        println("  reference: cloning $REFERENCE_URL")
        mkpath(REFS)
        run(`git clone --quiet $REFERENCE_URL $REFERENCE`)
    end
    run(pipeline(`git -C $REFERENCE checkout --quiet $REFERENCE_COMMIT`;
        stderr = devnull))
    sha = readchomp(`git -C $REFERENCE rev-parse --short HEAD`)
    println("  reference: pinned at $sha")
    return nothing
end

function write_wrapper()
    mkpath(joinpath(ORACLE, "src"))
    write(joinpath(ORACLE, "Cargo.toml"), CARGO_TOML)
    write(joinpath(ORACLE, "src", "main.rs"), MAIN_RS)
    println("  wrapper:   written to ", relpath(ORACLE, ROOT),
        " (GPL-3, gitignored, never distributed)")
    return nothing
end

function main()
    println("\n  oracle setup — opt-in, deliberately not part of CI\n")

    have(`git`) || (println("  git is required."); return 1)
    if !have(`cargo`)
        println("  cargo is not installed, so the oracle cannot be built.")
        println("  Everything else in the project works without it; `just verify`")
        println("  never needs a Rust toolchain.")
        return 1
    end

    fetch_reference()
    write_wrapper()

    println("  building…")
    ok = try
        success(`cargo build --release --quiet --manifest-path $(joinpath(ORACLE, "Cargo.toml"))`)
    catch
        false
    end
    ok || (println("\n  build failed."); return 1)

    println("  built:     ", relpath(joinpath(ORACLE, "target", "release", "om-oracle"), ROOT))
    println("\n  Now run `just oracle`.\n")
    return 0
end

exit(main())
